const wordList = [
  { word: "guitar", hint: "A musical instrument with strings." },
  { word: "oxygen", hint: "A colorless, odorless gas essential for life." },
  { word: "pizza", hint: "A savory dish consisting of a round, flattened base with toppings." },
  { word: "jazz", hint: "A genre of music characterized by improvisation and syncopation." },
  { word: "camera", hint: "A device used to capture and record images or videos." },
  { word: "novel", hint: "A long work of fiction, typically with a complex plot and characters." },
  { word: "ballet", hint: "A classical dance form characterized by precise and graceful movements." },
  { word: "planet", hint: "A celestial body that orbits a star and does not produce light of its own." },
  { word: "river", hint: "A large natural stream of water flowing in a channel to the sea, a lake, or another such stream." },
  { word: "breeze", hint: "A gentle wind." },
  { word: "oasis", hint: "A fertile spot in a desert where water is found." },
  { word: "safari", hint: "An expedition or journey, typically to observe wildlife in their natural habitat." },
  { word: "puzzle", hint: "A game, toy, or problem designed to test ingenuity or knowledge." },
  { word: "shadow", hint: "A dark area or shape produced by an object blocking the light." },
  { word: "secret", hint: "Something kept hidden or unknown to others." },
  { word: "unveil", hint: "To make known or reveal something previously secret or unknown." },
  { word: "robot", hint: "A machine that can perform tasks like a human." },
  { word: "html", hint: "Standard markup language for creating web pages." },
  { word: "css", hint: "Language used to style HTML elements." },
  { word: "react", hint: "A JavaScript library for building user interfaces." },
  { word: "api", hint: "Interface allowing communication between different software." },
  { word: "srk", hint: "The King of Romance in Bollywood." },
  { word: "k3g", hint: "A family drama featuring 'It's all about loving your parents'." },
  { word: "wicket", hint: "Something a bowler tries to take." },
  { word: "umpire", hint: "Person who makes decisions on the field." },
  { word: "sixer", hint: "A shot that crosses the boundary without bouncing." },
  { word: "yorker", hint: "A delivery that hits the batsman’s feet." },
  { word: "googly", hint: "A deceptive delivery by a leg-spinner." },
  { word: "burger", hint: "Fast food with a patty between buns." },
  { word: "pasta", hint: "Italian dish often served with sauce and cheese." },
  { word: "momos", hint: "Steamed or fried dumplings popular in India." },
  { word: "juice", hint: "Drink made by extracting liquid from fruits." },
  { word: "chai", hint: "Popular Indian spiced tea." },
  { word: "emoji", hint: "A digital icon used to express emotion." },
  { word: "robot", hint: "A machine that can perform tasks like a human." }
];
